version: "3"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - ngrok-helper
    ports:
      - "${PORT}:${PORT}"
    expose:
      - ${PORT}
    networks:
      main:
        aliases:
          - api
    command: ["npm", "run", "start.dev"]

  ngrok-helper:
    image: wernight/ngrok
    ports:
      - "0.0.0.0:${NGROK_HELPER_PORT}:${NGROK_HELPER_PORT}"
    expose:
      - ${NGROK_HELPER_PORT}
    environment: 
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_PORT: api:${PORT}
    networks:
      main:
        aliases:
          - helper

networks:
  main:


